#name: build
#on:
#  push:
#    branches:
#      - main
#jobs:
#  gobuild:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Setup Go 1.21
#        uses: actions/setup-go@v4
#        with:
#          go-version: '1.21'
#          cache: true
#      - name: Build
#        run: cd cmd && go build .
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-go@v5
#        with:
#          go-version: '1.21'
#          cache: true
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v4
#        with:
#          version: v1.57.2
