name: build
on:
 push:
   branches:
     - main
 pull_request:
    branches:
      - main
jobs:
 tests:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Setup Go 1.21
       uses: actions/setup-go@v4
       with:
         go-version: '1.21'
         cache: true
     - name: Test
       run: cd contest && go test -v ./api ./internal && cd ../testing && go test -v ./pkg
 lint:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       directory: [contest, remote_worker, testing ]
   steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-go@v5
       with:
         go-version: '1.21'
         cache: true
     - name: Linter
       uses: golangci/golangci-lint-action@v4
       with:
         version: latest
         working-directory: ${{ matrix.directory }}
