name: build
on:
 push:
   branches:
     - main
 pull_request:
    branches:
      - main
jobs:
 tests:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Setup Go 1.21
       uses: actions/setup-go@v4
       with:
         go-version: '1.21'
         cache: true
     - name: Test
       run: cd contest && go test -v ./api ./internal && cd ../testing && go test -v ./pkg
 resolve-modules:
   name: Resolve Modules
   runs-on: ubuntu-latest
   outputs:
     matrix: ${{ steps.set-matrix.outputs.matrix }}
   steps:
     - name: Checkout Sources
       uses: actions/checkout@v2
     - id: set-matrix
       run: ./ci-tools/resolve-modules.sh
 lint:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-go@v5
       with:
         go-version: '1.21'
         cache: true
     - name: Linter
       uses: golangci/golangci-lint-action@v4
       with:
         version: v1.57.2
         working-directory: ${{ matrix.workdir }}
